version: '3.3'
services:
  mongo-msg:
    image: mongo:latest
    container_name: crypto_0001
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
      MONGO_INITDB_DATABASE: CRYPTO_MSG
    ports:
      - "27017"
    volumes:
      - msg_data:/data/db
  mongo-key:
    image: mongo:latest
    container_name: crypto_0002
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
      MONGO_INITDB_DATABASE: CRYPTO_KEY
    ports:
      - "27017"
    volumes:
      - key_data:/data/db
volumes:
  msg_data:
  key_data: